# -*- coding: utf-8 -*-
"""Studymate.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQOYh4Z6PiSP34cVaZ_9YlVaCAZMa0np
"""

!pip install -q transformers accelerate sentence-transformers gradio pypdf faiss-cpu

import gradio as gr
from transformers import pipeline
from sentence_transformers import SentenceTransformer
from pypdf import PdfReader
import faiss

# Load models
llm = pipeline("text2text-generation", model="google/flan-t5-base", tokenizer="google/flan-t5-base", max_new_tokens=256)
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# PDF processing
def process_pdf(pdf_file):
    reader = PdfReader(pdf_file.name)
    texts = []
    for page in reader.pages:
        text = page.extract_text()
        if text:
            texts.append(text.strip())
    embeddings = embedder.encode(texts)
    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(embeddings)
    return texts, embeddings, index

pdf_data = {"texts": None, "embeddings": None, "index": None}

# Fast Q&A
def answer_question(question):
    if pdf_data["texts"] is None:
        return "❌ Upload a PDF first."
    q_emb = embedder.encode([question])
    _, I = pdf_data["index"].search(q_emb, 1)
    context = pdf_data["texts"][I[0][0]]
    prompt = f"""
You are a helpful tutor. Use only the context below to answer the question clearly and concisely in 2–3 sentences. If the answer is not in the context, say "Not in document."

Context:
{context}

Question: {question}
"""
    response = llm(prompt)[0]["generated_text"].strip()
    if "Not in document" in response or len(response.split()) < 5:
        return "⚠️ The answer might not be in the document. Try rephrasing or uploading a more detailed PDF."
    return response

# Simplified Summary
def generate_summary():
    if pdf_data["texts"] is None:
        return "❌ Upload a PDF first."
    full_text = "\n".join(pdf_data["texts"])
    prompt = f"""
Summarize the following text in 5–7 simple bullet points.
Use clear, easy-to-understand language.
Avoid repetition and technical jargon.

Text:
{full_text}
"""
    return llm(prompt)[0]["generated_text"].strip()

# Flashcards
def generate_flashcards():
    if pdf_data["texts"] is None:
        return "❌ Upload a PDF first."
    full_text = "\n".join(pdf_data["texts"])
    prompt = f"""
Create 10 flashcards from this text. Format each as:

Term: <concept>
Definition: <brief explanation>

Text:
{full_text}
"""
    return llm(prompt)[0]["generated_text"].strip()

# Key Concepts (Formatted)
def generate_key_concepts():
    if pdf_data["texts"] is None:
        return "❌ Upload a PDF first."
    full_text = "\n".join(pdf_data["texts"])
    prompt = f"""
Extract 10 key concepts from this text.
Format each concept like this:

<Concept Title>
<Brief Explanation>

Do not number them. Leave a blank line between each concept.

Text:
{full_text}
"""
    return llm(prompt)[0]["generated_text"].strip()

# Gradio UI
with gr.Blocks(title="StudyMate — Fast AI PDF Tutor", theme=gr.themes.Soft()) as app:
    gr.Markdown("""
    <h1 style='text-align: center; color: #4CAF50;'>📚 StudyMate — Fast AI PDF Tutor</h1>
    <p style='text-align: center;'>Upload your PDF and explore summaries, flashcards, key concepts, and instant Q&A.</p>
    """)

    with gr.Tab("📄 Upload PDF"):
        gr.Markdown("### Step 1: Upload your PDF")
        pdf_file = gr.File(label="Upload PDF", file_types=[".pdf"])
        upload_btn = gr.Button("📥 Process PDF", variant="primary")
        upload_out = gr.Textbox(label="Status")
        def handle_upload(pdf):
            texts, emb, idx = process_pdf(pdf)
            pdf_data["texts"] = texts
            pdf_data["embeddings"] = emb
            pdf_data["index"] = idx
            return "✅ PDF processed!"
        upload_btn.click(handle_upload, inputs=pdf_file, outputs=upload_out)

    with gr.Tab("❓ Ask Questions"):
        gr.Markdown("### Step 2: Ask a question from your PDF")
        q_input = gr.Textbox(label="Your question")
        q_btn = gr.Button("💬 Get Answer", variant="primary")
        q_out = gr.Textbox(label="Answer", lines=5)
        q_btn.click(answer_question, inputs=q_input, outputs=q_out)

    with gr.Tab("📝 Summary"):
        gr.Markdown("### Step 3: Generate a simplified summary")
        sum_btn = gr.Button("🧠 Generate Summary", variant="primary")
        sum_out = gr.Textbox(label="Summary", lines=10)
        sum_btn.click(generate_summary, outputs=sum_out)

    with gr.Tab("📌 Flashcards"):
        gr.Markdown("### Step 4: Generate flashcards")
        flash_btn = gr.Button("🗂️ Generate Flashcards", variant="primary")
        flash_out = gr.Textbox(label="Flashcards", lines=10)
        flash_btn.click(generate_flashcards, outputs=flash_out)

    with gr.Tab("🧠 Key Concepts"):
        gr.Markdown("### Step 5: Extract key concepts")
        key_btn = gr.Button("🔍 Extract Key Concepts", variant="primary")
        key_out = gr.Textbox(label="Key Concepts", lines=10)
        key_btn.click(generate_key_concepts, outputs=key_out)

app.launch()